# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  udo:
    cmds:
      #- git add . 
      - git ci -m {{.CLI_ARGS}}
      - git push
      - git push github 